insert into propietario_entity (id, foto, nombre, celular, correo) values (1, 'http://dummyimage.com/246x100.png/ff4444/ffffff', 'Sherlock', 30644438, 'smccreery0@amazon.com');
insert into propietario_entity (id, foto, nombre, celular, correo) values (2, 'http://dummyimage.com/232x100.png/ff4444/ffffff', 'Winslow', 82225165, 'wmckomb1@live.com');
insert into propietario_entity (id, foto, nombre, celular, correo) values (3, 'http://dummyimage.com/117x100.png/5fa2dd/ffffff', 'Tootsie', 97836070, 'tstinchcombe2@slate.com');
insert into propietario_entity (id, foto, nombre, celular, correo) values (4, 'http://dummyimage.com/230x100.png/5fa2dd/ffffff', 'Harriet', 35812767, 'hneesham3@ebay.com');
insert into propietario_entity (id, foto, nombre, celular, correo) values (5, 'http://dummyimage.com/145x100.png/ff4444/ffffff', 'Katuscha', 2994656, 'ksheriff4@epa.gov');
insert into propietario_entity (id, foto, nombre, celular, correo) values (6, 'http://dummyimage.com/164x100.png/cc0000/ffffff', 'Zitella', 82265421, 'zfollos5@squarespace.com');
insert into propietario_entity (id, foto, nombre, celular, correo) values (7, 'http://dummyimage.com/198x100.png/dddddd/000000', 'Krystalle', 25047373, 'kstainton6@nytimes.com');
insert into propietario_entity (id, foto, nombre, celular, correo) values (8, 'http://dummyimage.com/232x100.png/dddddd/000000', 'Myrlene', 24276441, 'mcockshutt7@clickbank.net');
insert into propietario_entity (id, foto, nombre, celular, correo) values (9, 'http://dummyimage.com/169x100.png/dddddd/000000', 'Denny', 16114748, 'dbinnion8@weather.com');
insert into propietario_entity (id, foto, nombre, celular, correo) values (10, 'http://dummyimage.com/133x100.png/5fa2dd/ffffff', 'Dorothy', 48827140, 'dkettell9@reverbnation.com');

insert into vivienda_entity (nombre, precio, descripcion, fotos, tamano, estrato, restricciones, tipo, contacto, direccion, ocupada, coordX, coordY, propietario_id) values ('Manuel', 12, 'Lac canaliculi probe', 'http://dummyimage.com/130x100.png/5fa2dd/ffffff', 28, 2, 'Urethral biopsy', 0, 'mmeasures0@indiegogo.com', 'Room 1691', false, 27.37, 2.04, 1);
insert into vivienda_entity (nombre, precio, descripcion, fotos, tamano, estrato, restricciones, tipo, contacto, direccion, ocupada, coordX, coordY, propietario_id) values ('Giffer', 17, 'Opn reduc disloc-hand', 'http://dummyimage.com/154x100.png/dddddd/000000', 20, 1, 'Create cutanperiton fist', 2, 'gbeekman1@toplist.cz', 'Room 700', false, 91.78, 19.3, 2);
insert into vivienda_entity (nombre, precio, descripcion, fotos, tamano, estrato, restricciones, tipo, contacto, direccion, ocupada, coordX, coordY, propietario_id) values ('Nissie', 84, 'Aortocor bypas-2 cor art', 'http://dummyimage.com/244x100.png/ff4444/ffffff', 523, 2, 'Suture scrotal lacerat', 0, 'nchyuerton2@stanford.edu', 'Apt 818', false, 89.41, 75.29, 3);
insert into vivienda_entity (nombre, precio, descripcion, fotos, tamano, estrato, restricciones, tipo, contacto, direccion, ocupada, coordX, coordY, propietario_id) values ('Tybie', 67, 'Assisting exercise', 'http://dummyimage.com/129x100.png/dddddd/000000', 1069, 0, 'Parasitology-blood', 1, 'tbraunton3@over-blog.com', 'PO Box 93363', true, 10.28, 57.85, 4);
insert into vivienda_entity (nombre, precio, descripcion, fotos, tamano, estrato, restricciones, tipo, contacto, direccion, ocupada, coordX, coordY, propietario_id) values ('Sayers', 91, 'Rad pancreaticoduodenect', 'http://dummyimage.com/112x100.png/dddddd/000000', 5483, 0, 'Facial bone biopsy', 2, 'spotticary4@sun.com', 'Room 368', true, 77.09, 31.3, 5);
insert into vivienda_entity (nombre, precio, descripcion, fotos, tamano, estrato, restricciones, tipo, contacto, direccion, ocupada, coordX, coordY, propietario_id) values ('Kala', 72, 'Int/comb version w extr', 'http://dummyimage.com/129x100.png/5fa2dd/ffffff', 5790, 1, 'Parasitology NOS', 1, 'ktivnan5@dropbox.com', '5th Floor', true, 33.31, 78.66, 6);
insert into vivienda_entity (nombre, precio, descripcion, fotos, tamano, estrato, restricciones, tipo, contacto, direccion, ocupada, coordX, coordY, propietario_id) values ('Charlton', 46, 'Open reduc-dislocat NEC', 'http://dummyimage.com/165x100.png/dddddd/000000', 1663, 4, 'Rectocele repair', 1, 'chappert6@angelfire.com', 'Suite 4', true, 51.09, 62.45, 7);
insert into vivienda_entity (nombre, precio, descripcion, fotos, tamano, estrato, restricciones, tipo, contacto, direccion, ocupada, coordX, coordY, propietario_id) values ('Quill', 59, 'Eswl gb/bile duct', 'http://dummyimage.com/133x100.png/dddddd/000000', 1036, 3, 'Muscle thermography', 0, 'qfursey7@nasa.gov', 'PO Box 95923', true, 41.65, 54.81, 8);
insert into vivienda_entity (nombre, precio, descripcion, fotos, tamano, estrato, restricciones, tipo, contacto, direccion, ocupada, coordX, coordY, propietario_id) values ('Raeann', 83, 'Open reduct maxillary fx', 'http://dummyimage.com/207x100.png/ff4444/ffffff', 1036, 0, 'Periph ganglionect NEC', 2, 'rlawlance8@icq.com', 'PO Box 66377', false, 56.99, 63.91, 9);
insert into vivienda_entity (nombre, precio, descripcion, fotos, tamano, estrato, restricciones, tipo, contacto, direccion, ocupada, coordX, coordY, propietario_id) values ('Garvin', 2, 'Carotid pulse tracing', 'http://dummyimage.com/200x100.png/dddddd/000000', 622, 3, 'Sclera reinforcement NEC', 0, 'gmcelhargy9@theglobeandmail.com', 'Room 392', true, 53.93, 39.88, 10);

insert into habitante_entity (id, cedula, nombre , vivienda_id) values (1, 709146542, 'Avie Rideout', 1);
insert into habitante_entity (id, cedula, nombre , vivienda_id) values (2, 288408031, 'Lurline Chastang', 2);
insert into habitante_entity (id, cedula, nombre , vivienda_id) values (3, 131580995, 'Tiffani Merwood', 3);
insert into habitante_entity (id, cedula, nombre , vivienda_id) values (4, 592506303, 'Rasia Danby', 4);
insert into habitante_entity (id, cedula, nombre , vivienda_id) values (5, 479790538, 'Rafaello Blackwell', 5);
insert into habitante_entity (id, cedula, nombre , vivienda_id) values (6, 465310691, 'Giacobo Dripp', 6);
insert into habitante_entity (id, cedula, nombre , vivienda_id) values (7, 785171550, 'Tully Mathivon', 7);
insert into habitante_entity (id, cedula, nombre , vivienda_id) values (8, 027248530, 'Natty Kubera', 8);
insert into habitante_entity (id, cedula, nombre , vivienda_id) values (9, 499702625, 'Heidi January', 9);
insert into habitante_entity (id, cedula, nombre , vivienda_id) values (10, 499807986, 'Sigismond Schmidt', 10);

insert into lugar_entity (id, nombre, coordenadax, coordenaday, fotos, gratis, precio_max, precio_min, tiempo_llegada, tipo) values (1, 'Huel, Goyette and Prohaska', 970, 586, 'http://dummyimage.com/198x100.png/5fa2dd/ffffff', false, 945, 80, 216, 1);
insert into lugar_entity (id, nombre, coordenadax, coordenaday, fotos, gratis, precio_max, precio_min, tiempo_llegada, tipo) values (2, 'Treutel, Stamm and Lubowitz', 342, 394, 'http://dummyimage.com/157x100.png/5fa2dd/ffffff', true, 981, 464, 294, 0);
insert into lugar_entity (id, nombre, coordenadax, coordenaday, fotos, gratis, precio_max, precio_min, tiempo_llegada, tipo) values (3, 'Dickens-Balistreri', 936, 534, 'http://dummyimage.com/124x100.png/5fa2dd/ffffff', false, 952, 201, 209, 1);
insert into lugar_entity (id, nombre, coordenadax, coordenaday, fotos, gratis, precio_max, precio_min, tiempo_llegada, tipo) values (4, 'Adams and Sons', 672, 236, 'http://dummyimage.com/206x100.png/5fa2dd/ffffff', false, 840, 343, 73, 2);
insert into lugar_entity (id, nombre, coordenadax, coordenaday, fotos, gratis, precio_max, precio_min, tiempo_llegada, tipo) values (5, 'Schuppe LLC', 940, 934, 'http://dummyimage.com/139x100.png/dddddd/000000', false, 852, 35, 159, 2);
insert into lugar_entity (id, nombre, coordenadax, coordenaday, fotos, gratis, precio_max, precio_min, tiempo_llegada, tipo) values (6, 'Ruecker-Kub', 620, 412, 'http://dummyimage.com/146x100.png/cc0000/ffffff', false, 961, 376, 88, 4);
insert into lugar_entity (id, nombre, coordenadax, coordenaday, fotos, gratis, precio_max, precio_min, tiempo_llegada, tipo) values (7, 'Davis-Williamson', 503, 714, 'http://dummyimage.com/124x100.png/dddddd/000000', false, 723, 387, 229, 4);
insert into lugar_entity (id, nombre, coordenadax, coordenaday, fotos, gratis, precio_max, precio_min, tiempo_llegada, tipo) values (8, 'Nicolas-Sauer', 981, 489, 'http://dummyimage.com/202x100.png/cc0000/ffffff', true, 922, 439, 13, 2);
insert into lugar_entity (id, nombre, coordenadax, coordenaday, fotos, gratis, precio_max, precio_min, tiempo_llegada, tipo) values (9, 'Schmitt, Bauch and Powlowski', 304, 830, 'http://dummyimage.com/109x100.png/5fa2dd/ffffff', true, 763, 104, 188, 3);
insert into lugar_entity (id, nombre, coordenadax, coordenaday, fotos, gratis, precio_max, precio_min, tiempo_llegada, tipo) values (10, 'Metz-Wiza', 970, 349, 'http://dummyimage.com/137x100.png/cc0000/ffffff', false, 512, 496, 127, 3);
insert into lugar_entity (id, nombre, coordenadax, coordenaday, fotos, gratis, precio_max, precio_min, tiempo_llegada, tipo) values (11, 'O''Reilly and Sons', 591, 114, 'http://dummyimage.com/206x100.png/5fa2dd/ffffff', false, 534, 233, 284, 2);
insert into lugar_entity (id, nombre, coordenadax, coordenaday, fotos, gratis, precio_max, precio_min, tiempo_llegada, tipo) values (12, 'Runolfsdottir LLC', 831, 229, 'http://dummyimage.com/231x100.png/cc0000/ffffff', true, 555, 399, 198, 4);
insert into lugar_entity (id, nombre, coordenadax, coordenaday, fotos, gratis, precio_max, precio_min, tiempo_llegada, tipo) values (13, 'Champlin Group', 27, 907, 'http://dummyimage.com/209x100.png/dddddd/000000', false, 565, 215, 174, 1);
insert into lugar_entity (id, nombre, coordenadax, coordenaday, fotos, gratis, precio_max, precio_min, tiempo_llegada, tipo) values (14, 'Morissette, Bernier and Moen', 14, 886, 'http://dummyimage.com/205x100.png/dddddd/000000', true, 910, 63, 212, 1);
insert into lugar_entity (id, nombre, coordenadax, coordenaday, fotos, gratis, precio_max, precio_min, tiempo_llegada, tipo) values (15, 'Connelly Group', 602, 947, 'http://dummyimage.com/100x100.png/ff4444/ffffff', true, 898, 207, 53, 0);

insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (5, 13);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (5, 4);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (8, 10);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (5, 12);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (6, 13);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (4, 12);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (9, 1);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (2, 9);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (9, 6);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (1, 12);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (4, 13);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (8, 10);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (4, 8);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (10, 6);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (7, 7);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (7, 5);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (4, 4);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (3, 4);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (9, 11);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (2, 12);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (1, 10);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (6, 6);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (9, 8);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (1, 1);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (7, 13);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (5, 14);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (9, 4);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (9, 6);
insert into VIVIENDA_ENTITY_LUGAR_DE_INTERES_CERCANO  (viviendas_cercanas_id, lugar_de_interes_cercano_id) values (7, 15);

insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (1, 9);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (4, 2);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (7, 9);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (10, 7);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (7, 10);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (1, 10);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (10, 4);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (2, 8);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (9, 5);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (1, 3);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (2, 4);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (1, 4);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (10, 10);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (9, 2);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (4, 8);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (3, 4);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (4, 9);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (1, 1);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (5, 10);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (9, 7);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (7, 5);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (2, 4);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (6, 9);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (10, 4);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (5, 4);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (7, 3);
insert into VIVIENDA_ENTITY_HISTORIAL (viviendas_id, historial_id) values (1, 7);

nsert into SERVICIO_ENTITY (id, nombre, costo_adicional, tipo) values (1, 'Mydo', 420317, 0);
insert into SERVICIO_ENTITY (id, nombre, costo_adicional, tipo) values (2, 'Katz', 609437, 2);
insert into SERVICIO_ENTITY (id, nombre, costo_adicional, tipo) values (3, 'Fadeo', 728832, 1);
insert into SERVICIO_ENTITY (id, nombre, costo_adicional, tipo) values (4, 'Brightbean', 963828, 4);
insert into SERVICIO_ENTITY (id, nombre, costo_adicional, tipo) values (5, 'Tagfeed', 261183, 2);
insert into SERVICIO_ENTITY (id, nombre, costo_adicional, tipo) values (6, 'Kwilith', 827956, 2);
insert into SERVICIO_ENTITY (id, nombre, costo_adicional, tipo) values (7, 'Skynoodle', 324760, 1);
insert into SERVICIO_ENTITY (id, nombre, costo_adicional, tipo) values (8, 'Jaxworks', 549510, 3);
insert into SERVICIO_ENTITY (id, nombre, costo_adicional, tipo) values (9, 'Snaptags', 504635, 0);
insert into SERVICIO_ENTITY (id, nombre, costo_adicional, tipo) values (10, 'Kamba', 86993, 2);

insert into comentario_entity (id,titulo, texto, calificacion , nombre) values (1, 'Buen servicio', 'la persona que nos atendió brindo un buen servicio', 5,'Sherlock');
insert into comentario_entity (id,titulo, texto, calificacion , nombre) values (2, 'fea vista', 'La vista no fue de mi agrado ya que un edificio tapa la visión', 3,'Winslow');
insert into comentario_entity (id,titulo, texto, calificacion , nombre) values (3, 'linda vista', 'Me gusto la vista ya que da a la avenida', 4,'Katushka');
insert into comentario_entity (id,titulo, texto, calificacion , nombre) values (4, 'es lo que esperaba', 'El apartamento es justamente como en las publicaciones', 5,'Garvin');
insert into comentario_entity (id,titulo, texto, calificacion , nombre) values (5, 'no es lo que esperaba', 'no es nada parecido al de las publicaciones', 2,'Sayers');
insert into comentario_entity (id,titulo, texto, calificacion , nombre) values (6, 'buena ubicación', 'Esta muy cerca de mi universidad', 5,'Tybie');
insert into comentario_entity (id,titulo, texto, calificacion , nombre) values (7, 'mala ubiacion', 'Es muy lejos de mi universidad', 2,'Quill');
insert into comentario_entity (id,titulo, texto, calificacion , nombre) values (8, 'centralizado', 'Al estar en el centro de la ciudad, tengo acceso a lugares muy rapidamente', 4,'Dorothy');
insert into comentario_entity (id,titulo, texto, calificacion , nombre) values (9, 'no centralizado', ' queda muy lejos de todo al no estar en el centro de la ciudad', 3,'Denny');
insert into comentario_entity (id,titulo,texto, calificacion , nombre) values (10, 'buen piso', 'Me gustaron mucho el diseño de las baldosas', 3,'Zitella');
